experiment_name: "svm_qkernel_fashion_mnist_exp"
binary_classes: [3, 8]

dataset:
  name: "fashion_mnist"
  binary_classes: [3, 8]
  grayscale: true
  root: "./data"

pennylane:
  device: "lightning.gpu"
  workers: 0
  tile_size: 128
  kernel_centering: true

svm:
  use_pca: false
  pca_components: 50

optuna:
  n_trials: 30

checkpoint:
  save_dir: "checkpoints"
  subdir: "fashion_mnist_svm_qkernel"
