experiment_name: "svm_qkernel_fashion_mnist_debug_exp"

dataset:
  name: fashion_mnist
  binary_classes: [3, 8]   # Pull vs Bag
  grayscale: true
  augment: false
  root: ./data

pennylane:
  device: "lightning.qubit"
  workers: 0
  tile_size: 32
  kernel_centering: true

svm:
  use_pca: false
  pca_components: 50

optuna:
  n_trials: 30

checkpoint:
  save_dir: "checkpoints"
  subdir: "fashion_mnist_svm_qkernel_debug"
