# config/fashion_mnist_qsvm_optimized.yaml
experiment_name: "svm_qkernel_fashion_mnist_blackwell_float64"

dataset:
  name: fashion_mnist
  binary_classes: [0, 6]     # T-shirt/top vs Shirt (exemple difficile)
  grayscale: true
  root: ./data

pennylane:
  device: lightning.gpu
  workers: 1
  layers: 2
  tile_size: 12000           # On peut monter encore plus haut ici
  kernel_centering: true
  gram_backend: cuda_states
  angle_scale: 1.5
  embed_mode: ryrz

svm:
  use_pca: true
  pca_components: 10
  n_trials: 40

cv_folds: 3