experiment_name: "svm_qkernel_fashion_mnist_final_float64"

dataset:
  name: fashion_mnist
  binary_classes: [3, 8]     # T-shirt/top vs Shirt
  grayscale: true
  root: ./data

pennylane:
  layers: 1

svm:
  n_trials: 30

cv_folds: 3