experiment_name: "svhn_hybrid_qcnn_svm_tiny_debug"
binary_classes: [3, 8]

dataset:
  name: "svhn"
  binary_classes: [3, 8]
  grayscale: false
  root: "./data"

svm:
  n_trials: 10

pennylane:
  device: "lightning.qubit"
  workers: 0
  tile_size: 32
  kernel_centering: true
