experiment_name: "svhn_hybrid_qcnn_svm_large_quality"
binary_classes: [3, 8]

dataset:
  name: "svhn"
  binary_classes: [3, 8]
  grayscale: false
  root: "./data"

svm:
  n_trials: 60

pennylane:
  device: "lightning.gpu"
  kernel_centering: true
