# config/svhn_qsvm_optimized.yaml
experiment_name: "svm_qkernel_svhn_blackwell_float64"

dataset:
  name: svhn
  binary_classes: [3, 8]
  grayscale: true
  root: ./data

pennylane:
  device: lightning.gpu      # Passage sur GPU
  workers: 1
  layers: 2
  tile_size: 10000           # Gros batch
  kernel_centering: true
  gram_backend: cuda_states  # Activation du backend custom
  angle_scale: 1.5
  embed_mode: ryrz

svm:
  use_pca: true
  pca_components: 10
  n_trials: 30

cv_folds: 3